// Shared by the static home, workshop lightbox and live catalogue section.
const copy = {
  ko: {
    mobileShop: '샵 · 전체 상품 <span>↗</span>', shopAll: '전체 상품 보기',
    shopIndex: '지도칸 / 샵', shopTitle: '지도칸의<br><em>모든 제품.</em>',
    shopDescription: '복싱화부터 함께하는 아이템까지.<br>지도칸의 전체 상품을 만나보세요.',
    shopLoading: '상품을 불러오고 있습니다.', shopEmpty: '현재 진열된 상품이 없습니다.',
    shopPrevious: '이전 상품', shopNext: '다음 상품', shopBrowse: '좌우로 넘겨 상품을 살펴보세요',
    craftIndex: '제작과정', craftTitle: '숙련된 손으로,<br><em>한 켤레씩 정성껏.</em>',
    craftDescription: '오랜 경험을 쌓아온 숙련 제작자들이 대한민국에서 한 켤레씩 수제로 제작합니다. 가죽 재단부터 갑피 제작, 밑창 접착까지 손으로 직접 완성합니다.',
    craftGallery: '지도칸 수제 복싱화 제작 과정', craftSwipe: '좌우로 넘겨 제작 과정을 살펴보세요',
    craftPrevious: '이전 제작 사진', craftNext: '다음 제작 사진', craftDialogIndex: '지도칸 / 제작과정',
    craftPhoto0: '재단', craftPhoto1: '갑피', craftPhoto2: '갑피', craftPhoto3: '밑창 접착',
    craftPhoto0Alt: '초록색 가죽 위에 패턴을 대고 선을 그리는 작업',
    craftPhoto1Alt: '초록색 가죽과 흰색 메쉬 부위를 손으로 맞추는 작업',
    craftPhoto2Alt: '검정색과 흰색 복싱화 갑피의 형태를 다듬는 작업',
    craftPhoto3Alt: '파란색 복싱화의 밑창 가장자리를 손으로 마감하는 작업',
  },
  en: {
    mobileShop: 'Shop · All products <span>↗</span>', shopAll: 'View all products',
    shopIndex: 'JIDOKAAN / Shop', shopTitle: 'Discover<br><em>JIDOKAAN.</em>',
    shopDescription: 'From boxing shoes to the gear that goes with them.<br>Explore the full JIDOKAAN range.',
    shopLoading: 'Loading products.', shopEmpty: 'No products are currently on display.',
    shopPrevious: 'Previous products', shopNext: 'Next products', shopBrowse: 'Swipe to explore the products',
    craftIndex: 'Making process', craftTitle: 'Experienced hands.<br><em>One pair at a time.</em>',
    craftDescription: 'Our experienced makers handcraft each pair with care in South Korea. From cutting the leather to making the uppers and bonding the soles, every pair takes shape by hand.',
    craftGallery: 'How JIDOKAAN boxing shoes are handcrafted', craftSwipe: 'Swipe to explore the making process',
    craftPrevious: 'Previous workshop photo', craftNext: 'Next workshop photo', craftDialogIndex: 'JIDOKAAN / Making process',
    craftPhoto0: 'Cutting', craftPhoto1: 'Upper', craftPhoto2: 'Upper', craftPhoto3: 'Sole bonding',
    craftPhoto0Alt: 'Tracing a pattern onto green leather by hand',
    craftPhoto1Alt: 'Aligning green leather and white mesh panels by hand',
    craftPhoto2Alt: 'Shaping the upper of a black and white boxing shoe',
    craftPhoto3Alt: 'Finishing the edge of the sole on a blue boxing shoe by hand',
  },
  ja: {
    mobileShop: 'ショップ・全商品 <span>↗</span>', shopAll: 'すべての商品を見る',
    shopIndex: 'JIDOKAAN / ショップ', shopTitle: 'JIDOKAANの<br><em>すべてのアイテム。</em>',
    shopDescription: 'ボクシングシューズから、一緒に使うアイテムまで。<br>JIDOKAANの全商品をご覧ください。',
    shopLoading: '商品を読み込んでいます。', shopEmpty: '現在、掲載されている商品はありません。',
    shopPrevious: '前の商品', shopNext: '次の商品', shopBrowse: '左右にスワイプして商品をご覧ください',
    craftIndex: '製作工程', craftTitle: '熟練の手で、<br><em>一足ずつ丁寧に。</em>',
    craftDescription: '豊富な経験を持つ職人が、韓国で一足ずつ丁寧に手作りしています。革の裁断からアッパーの製作、ソールの接着まで、手作業で形にします。',
    craftGallery: 'JIDOKAANボクシングシューズの製作工程', craftSwipe: '左右にスワイプして製作工程をご覧ください',
    craftPrevious: '前の製作写真', craftNext: '次の製作写真', craftDialogIndex: 'JIDOKAAN / 製作工程',
    craftPhoto0: '裁断', craftPhoto1: 'アッパー', craftPhoto2: 'アッパー', craftPhoto3: 'ソール接着',
    craftPhoto0Alt: '緑色の革に型紙を当てて線を引く作業',
    craftPhoto1Alt: '緑色の革と白いメッシュのパーツを手で合わせる作業',
    craftPhoto2Alt: '黒と白のボクシングシューズのアッパーを整える作業',
    craftPhoto3Alt: '青いボクシングシューズのソールの縁を手で仕上げる作業',
  },
  zh: {
    mobileShop: '商店 · 全部商品 <span>↗</span>', shopAll: '查看全部商品',
    shopIndex: 'JIDOKAAN / 商店', shopTitle: '探索 JIDOKAAN<br><em>全系列产品。</em>',
    shopDescription: '从拳击鞋到搭配使用的装备，<br>浏览 JIDOKAAN 的全部商品。',
    shopLoading: '正在加载商品。', shopEmpty: '目前暂无展示商品。',
    shopPrevious: '上一组商品', shopNext: '下一组商品', shopBrowse: '左右滑动浏览商品',
    craftIndex: '制作过程', craftTitle: '经验丰富的双手，<br><em>用心制作每一双。</em>',
    craftDescription: '经验丰富的制鞋师在韩国逐双手工制作。从皮革裁切、鞋面制作到鞋底粘合，每一双都由双手细心完成。',
    craftGallery: 'JIDOKAAN 手工拳击鞋制作过程', craftSwipe: '左右滑动了解制作过程',
    craftPrevious: '上一张制作照片', craftNext: '下一张制作照片', craftDialogIndex: 'JIDOKAAN / 制作过程',
    craftPhoto0: '裁切', craftPhoto1: '鞋面', craftPhoto2: '鞋面', craftPhoto3: '鞋底粘合',
    craftPhoto0Alt: '在绿色皮革上按照纸样描线',
    craftPhoto1Alt: '用手对齐绿色皮革与白色网布部件',
    craftPhoto2Alt: '整理黑白拳击鞋的鞋面形状',
    craftPhoto3Alt: '用手修整蓝色拳击鞋的鞋底边缘',
  },
  es: {
    mobileShop: 'Tienda · Todos los productos <span>↗</span>', shopAll: 'Ver todos los productos',
    shopIndex: 'JIDOKAAN / Tienda', shopTitle: 'Descubre<br><em>JIDOKAAN.</em>',
    shopDescription: 'Desde botas de boxeo hasta los accesorios que las acompañan.<br>Explora todos los productos JIDOKAAN.',
    shopLoading: 'Cargando productos.', shopEmpty: 'No hay productos disponibles para mostrar.',
    shopPrevious: 'Productos anteriores', shopNext: 'Productos siguientes', shopBrowse: 'Desliza para explorar los productos',
    craftIndex: 'Proceso de fabricación', craftTitle: 'Manos expertas.<br><em>Un par a la vez.</em>',
    craftDescription: 'Nuestros artesanos experimentados elaboran cada par con esmero en Corea del Sur. Desde cortar el cuero hasta confeccionar las capelladas y pegar las suelas, cada par se hace a mano.',
    craftGallery: 'El proceso artesanal de las botas de boxeo JIDOKAAN', craftSwipe: 'Desliza para explorar el proceso de fabricación',
    craftPrevious: 'Foto anterior del taller', craftNext: 'Foto siguiente del taller', craftDialogIndex: 'JIDOKAAN / Proceso de fabricación',
    craftPhoto0: 'Corte', craftPhoto1: 'Capellada', craftPhoto2: 'Capellada', craftPhoto3: 'Pegado de la suela',
    craftPhoto0Alt: 'Trazado de un patrón a mano sobre cuero verde',
    craftPhoto1Alt: 'Alineación a mano de piezas de cuero verde y malla blanca',
    craftPhoto2Alt: 'Trabajo de forma del corte de una bota de boxeo negra y blanca',
    craftPhoto3Alt: 'Acabado a mano del borde de la suela de una bota de boxeo azul',
  },
};
export default copy;
