export default  {
  "en": {
    "faqIndex": "04 / Before you order",
    "faqTitle": "Questions<br><em>& answers.</em>",
    "faqIntro": "From ordering to caring for your pair.",
    "navFaq": "FAQ",
    "identityCaption": "JIDOKAAN is<br><strong>made in South Korea.</strong>",
    "emblemAlt": "JIDOKAAN — Made in Korea logo",
    "process2": "Save your design & order",
    "process2Description": "Save a screenshot of your selected colours. For orders within South Korea, place your order through Naver Smart Store.",
    "process3": "Check Naver TalkTalk",
    "process3Description": "After ordering, be sure to read the Naver TalkTalk message sent by our team.",
    "orderIndex": "05 / Create your boxing shoes",
    "faqQ1": "How do I place an order?",
    "faqA1": "<ol><li>Create your preferred colour combination in the simulator on this site.</li><li>Take and save a screenshot of your finished design.</li><li>For orders within South Korea, place your order through our Naver Smart Store.</li><li>After ordering, <strong>check the Naver TalkTalk message sent by our team.</strong></li></ol>",
    "faqQ2": "How long does production take?",
    "faqA2": "<p>Please allow approximately <strong>30 business days</strong> for production. Orders are usually dispatched within 2–3 weeks on average, but timing may vary with order volume and material availability.</p><p>Shipping time after dispatch is additional.</p>",
    "faqQ3": "How should I choose my size?",
    "faqA3": "<p>Customers with wide feet who usually wear the same size across different shoes have often reported a good fit in that same JIDOKAAN size.</p><p>For a standard foot shape, we generally recommend <strong>one size down</strong> from your usual Nike or Adidas trainers. Fit varies by brand, model and foot shape. If unsure, tell us the model and size you normally wear before ordering.</p>",
    "faqQ4": "Can I exchange or return my shoes?",
    "faqA4": "<p>Each pair is made individually to your specifications and is difficult to resell. Change-of-mind exchanges and returns are restricted <strong>where the legal conditions are met, including separate advance notice and written or electronic consent.</strong></p><p>If we confirm a manufacturing defect or a deviation from your order, we will advise on free repair or remaking under the same specifications. We assess the order details, product condition and manufacturing criteria together. Statutory rights to exchange or refund remain unaffected.</p>",
    "faqQ5": "How much do the shoes weigh?",
    "faqA5": "<p>Approximately <strong>280 g for size 260</strong>. Weight can vary slightly with the selected materials and configuration.</p>",
    "faqQ6": "Can the outsole be repaired or replaced?",
    "faqA6": "<p>We offer repair support if the outsole separates during use or needs replacement.</p><ul><li><strong>Minor reinforcement: free for six months</strong></li><li><strong>Outsole replacement: KRW 60,000</strong></li></ul><p>Please contact us with photos showing the condition before sending in your shoes.</p>",
    "faqQ7": "Can I wash the shoes?",
    "faqA7": "<p>You may gently wipe soiled fabric areas with a small amount of mild detergent. As the primary material is cowhide, <strong>machine washing, soaking and washing the entire shoe with water are not recommended.</strong></p>",
    "faqQ8": "Can I order different sizes for my left and right feet?",
    "faqA8": "<p><strong>Yes.</strong> We recommend this only if you have already worn JIDOKAAN shoes and know the correct size for each foot.</p><p>We do not recommend ordering different left and right sizes without first knowing your JIDOKAAN fit.</p>",
    "faqQ9": "What goes into the price?",
    "faqA9": "<p>JIDOKAAN shoes are <strong>handcrafted one pair at a time in South Korea</strong>, in the combination chosen by each customer. Each pair requires more than ten hours of work, excluding adhesive drying time.</p><p>The price reflects skilled makers’ working time and labour costs, as well as the cost of materials.</p>",
    "faqQ10": "What finish should I expect from handmade shoes?",
    "faqA10": "<p>Handcrafting is a <strong>production method</strong> that allows us to make a pair to an individual’s request. It does not mean that every part is completely free from minor variation.</p><p>Small differences in stitch spacing or finishing may occur during handwork. We distinguish these characteristics from manufacturing defects that affect function or durability.</p>",
    "mobileFaq": "FAQ <span>04</span>",
    "look0": "White · Gold",
    "look1": "Navy · White",
    "look2": "Red · Black",
    "look3": "Green · Red",
    "look4": "Silver · Gold",
    "look5": "White · Red",
    "look6": "Pink · Black",
    "look7": "Yellow · Black",
    "look8": "Black · Gold",
    "look9": "All White",
    "look10": "White · Black",
    "specialDescription": "Special orders can use leathers beyond our standard range, as well as materials with special patterns or textures.<br><br>The special-order simulator is in preparation. You can find a variety of special-order examples on the product detail pages of our website.<br><br><strong>Before placing a special order, please contact us via Naver TalkTalk message or by calling our customer service number.</strong>",
    "collectionDescription": "From understated white to bold colour combinations.<br>Find a combination that speaks to you.",
    "galleryLabel": "Eleven custom-order shoe examples",
    "specialContact": "Customer service: 010-3481-5598 ↗"
  },
  "ja": {
    "faqIndex": "04 / ご注文の前に",
    "faqTitle": "よくある<br><em>ご質問。</em>",
    "faqIntro": "ご注文からお手入れまで。",
    "navFaq": "よくある質問",
    "identityCaption": "JIDOKAANは<br><strong>韓国で製作しています。</strong>",
    "emblemAlt": "JIDOKAAN — Made in Korea ロゴ",
    "process2": "デザインを保存して注文",
    "process2Description": "選んだ配色のスクリーンショットを保存してください。韓国国内のご注文はNaverスマートストアでお手続きいただけます。",
    "process3": "Naver TalkTalkを確認",
    "process3Description": "注文後、担当者から届くNaver TalkTalkのメッセージを必ずご確認ください。",
    "orderIndex": "05 / 自分だけのシューズを作る",
    "faqQ1": "どのように注文しますか？",
    "faqA1": "<ol><li>このサイトのシミュレーターで、お好みの配色を完成させてください。</li><li>完成したデザインのスクリーンショットを保存してください。</li><li>韓国国内からのご注文は、Naverスマートストアでお手続きください。</li><li>ご注文後、担当者から届く<strong>Naver TalkTalkのメッセージを必ずご確認ください。</strong></li></ol>",
    "faqQ2": "注文からどのくらいかかりますか？",
    "faqA2": "<p>製作期間は<strong>約30営業日</strong>を目安にお考えください。平均では2〜3週間以内に出荷していますが、受注量や素材の入荷状況により変動する場合があります。</p><p>出荷後の配送期間は別途かかります。</p>",
    "faqQ3": "サイズはどのように選びますか？",
    "faqA3": "<p>足幅が広く、普段さまざまな靴を同じサイズで履いている方からは、JIDOKAANも同じサイズで合ったというお声を多くいただいています。</p><p>標準的な足型の方には、普段のナイキ・アディダスのスニーカーより<strong>ワンサイズ小さめ</strong>をお勧めしています。ただし、ブランド・モデル・足型により異なります。迷われる場合は、ご注文前に普段のモデルとサイズをお知らせください。</p>",
    "faqQ4": "交換・返品はできますか？",
    "faqA4": "<p>お客様のご要望に合わせて一足ずつ製作するため、再販売が難しい商品です。<strong>個別の事前告知と書面・電子文書による同意など、法定要件を満たす場合</strong>、お客様都合の交換・返品は制限されます。</p><p>製作上の不具合や注文内容との相違が確認された場合は、無償修理または同じ条件での再製作をご案内します。注文内容・製品の状態・製作基準を照合して確認し、関係法令に基づく交換・返金の権利は保障されます。</p>",
    "faqQ5": "製品の重さはどのくらいですか？",
    "faqA5": "<p><strong>260サイズで約280g前後</strong>です。選択する素材や構成によって多少異なります。</p>",
    "faqQ6": "アウトソールの交換や修理はできますか？",
    "faqA6": "<p>使用中にアウトソールが剥がれたり、交換が必要になった場合は修理に対応しています。</p><ul><li><strong>簡単な補強：6か月間無料</strong></li><li><strong>アウトソール交換：60,000韓国ウォン</strong></li></ul><p>修理をご依頼の際は、まず状態が分かる写真を添えてお問い合わせください。</p>",
    "faqQ7": "洗濯できますか？",
    "faqA7": "<p>布部分の汚れは、少量の刺激の弱い洗剤で軽く拭き取れます。主な素材が牛革のため、<strong>洗濯機の使用、つけ置き、製品全体の水洗いはお勧めしません。</strong></p>",
    "faqQ8": "左右で異なるサイズを製作できますか？",
    "faqA8": "<p><strong>可能です。</strong>ただし、すでにJIDOKAANを履いた経験があり、左右それぞれに合うサイズが分かっている方にお勧めします。</p><p>JIDOKAANのサイズ感が分からない状態で、左右別サイズをご注文いただくことはお勧めしません。</p>",
    "faqQ9": "価格はどのように決まりますか？",
    "faqA9": "<p>JIDOKAANは、お客様が選んだ組み合わせで<strong>韓国にて一足ずつ手作業で製作</strong>しています。一足の製作には、接着剤の乾燥時間を除いても10時間を超える作業が必要です。</p><p>販売価格には、熟練した職人の作業時間・人件費・素材費が反映されています。</p>",
    "faqQ10": "手作りの靴は、どのような仕上がりですか？",
    "faqA10": "<p>手作りとは、一人ひとりの要望に合わせて製作できる<strong>製法の違い</strong>です。すべての部分にわずかな差もないことを意味するものではありません。</p><p>手作業では、ステッチの間隔や仕上げに微細な違いが生じる場合があります。こうした特徴と、機能・耐久性に影響する製作上の不具合は区別して確認します。</p>",
    "mobileFaq": "よくある質問 <span>04</span>",
    "look0": "ホワイト · ゴールド",
    "look1": "ネイビー · ホワイト",
    "look2": "レッド · ブラック",
    "look3": "グリーン · レッド",
    "look4": "シルバー · ゴールド",
    "look5": "ホワイト · レッド",
    "look6": "ピンク · ブラック",
    "look7": "イエロー · ブラック",
    "look8": "ブラック · ゴールド",
    "look9": "オールホワイト",
    "look10": "ホワイト · ブラック",
    "specialDescription": "通常取り扱うレザー以外にも、別のレザーや特殊な柄・模様の素材を使って製作できます。<br><br>スペシャルオーダー用シミュレーターは準備中です。さまざまな製作例は、サイト内の商品詳細ページでご覧いただけます。<br><br><strong>スペシャルオーダーをご希望の場合は、ご注文前にNaver TalkTalkのメッセージ、またはカスタマーセンターへのお電話でご相談ください。</strong>",
    "collectionDescription": "上品なホワイトから、鮮やかな配色まで。<br>好みに合う組み合わせを見つけてください。",
    "galleryLabel": "11種類のカスタムオーダー製作例",
    "specialContact": "カスタマーセンター 010-3481-5598 ↗"
  },
  "zh": {
    "faqIndex": "04 / 下单之前",
    "faqTitle": "常见问题<br><em>与解答。</em>",
    "faqIntro": "从下单到日常保养。",
    "navFaq": "常见问题",
    "identityCaption": "JIDOKAAN<br><strong>在韩国制作。</strong>",
    "emblemAlt": "JIDOKAAN — 韩国制造标志",
    "process2": "保存设计并下单",
    "process2Description": "截取并保存所选配色。韩国境内订单请通过Naver Smart Store下单。",
    "process3": "查看Naver TalkTalk",
    "process3Description": "下单后，请务必查看工作人员发送的Naver TalkTalk消息。",
    "orderIndex": "05 / 设计我的拳击鞋",
    "faqQ1": "如何下单？",
    "faqA1": "<ol><li>在本网站的模拟器中完成您喜欢的配色组合。</li><li>截取并保存完成后的设计图片。</li><li>韩国境内订单请通过Naver Smart Store下单。</li><li>下单后，<strong>请务必查看工作人员发送的Naver TalkTalk消息。</strong></li></ol>",
    "faqQ2": "下单后需要多久？",
    "faqA2": "<p>制作周期请预留<strong>约30个工作日</strong>。通常平均在2至3周内发货，但具体时间可能因订单量和材料供应情况而有所变化。</p><p>发货后的运输时间另计。</p>",
    "faqQ3": "如何选择尺码？",
    "faqA3": "<p>对于脚掌较宽、平时不同鞋款都穿同一码数的顾客，较多反馈表明，选择相同尺码的JIDOKAAN较为合脚。</p><p>对于标准脚型，一般建议比平时穿的耐克或阿迪达斯运动鞋<strong>小一码</strong>。但不同品牌、鞋款及脚型存在差异。如有疑问，请在下单前告知平时穿的鞋款和尺码。</p>",
    "faqQ4": "可以换货或退货吗？",
    "faqA4": "<p>本产品根据每位顾客的要求逐双制作，难以再次销售。<strong>在满足单独事先告知、书面或电子文件同意等法定条件时</strong>，仅因个人改变主意而提出的退换货将受到限制。</p><p>如确认存在制作缺陷或与订单内容不符，我们会提供免费维修或按相同条件重新制作的处理说明。检查将结合订单、产品状态及制作标准进行；相关法律规定的退换货及退款权利不受影响。</p>",
    "faqQ5": "产品重量是多少？",
    "faqA5": "<p><strong>260尺码约为280克左右</strong>。重量可能因所选材料和配置而略有不同。</p>",
    "faqQ6": "可以更换外底或提供售后维修吗？",
    "faqA6": "<p>使用过程中出现外底开胶或需要更换时，我们提供维修支持。</p><ul><li><strong>简单加固：6个月内免费</strong></li><li><strong>外底更换：60,000韩元</strong></li></ul><p>申请维修前，请先提供能显示产品状态的照片并联系我们。</p>",
    "faqQ7": "可以清洗吗？",
    "faqA7": "<p>布料部位的污渍可以用少量温和洗涤剂轻轻擦拭。由于主要材料为牛皮，<strong>不建议机洗、浸泡或整鞋水洗。</strong></p>",
    "faqQ8": "左右脚可以制作成不同尺码吗？",
    "faqA8": "<p><strong>可以。</strong>但仅建议已穿过JIDOKAAN、了解左右脚合适尺码的顾客采用这种方式。</p><p>如果还不清楚JIDOKAAN的尺码和贴合度，不建议直接订购左右不同尺码。</p>",
    "faqQ9": "价格包含哪些成本？",
    "faqA9": "<p>JIDOKAAN按照每位顾客选择的组合，<strong>在韩国逐双手工制作</strong>。制作一双鞋，即使不计胶水干燥时间，也需要超过10小时的工作。</p><p>售价体现了熟练制鞋师的工作时间、人工成本及材料成本。</p>",
    "faqQ10": "应如何理解手工鞋的做工标准？",
    "faqA10": "<p>手工制作是为了满足个人要求而采用的<strong>制作工艺</strong>，并不意味着每个部位都完全没有细微差异。</p><p>手工过程中，针脚间距或收尾细节可能存在微小差别。我们会区分这些手工特征与影响功能、耐用性的制作缺陷。</p>",
    "mobileFaq": "常见问题 <span>04</span>",
    "look0": "白色 · 金色",
    "look1": "海军蓝 · 白色",
    "look2": "红色 · 黑色",
    "look3": "绿色 · 红色",
    "look4": "银色 · 金色",
    "look5": "白色 · 红色",
    "look6": "粉色 · 黑色",
    "look7": "黄色 · 黑色",
    "look8": "黑色 · 金色",
    "look9": "纯白",
    "look10": "白色 · 黑色",
    "specialDescription": "特别定制可采用常备皮革以外的其他皮革，以及特殊图案、纹理的材料。<br><br>特别定制模拟器正在筹备中。您可以在网站的产品详情页查看多种特别定制示例。<br><br><strong>如需特别定制，请在下单前通过Naver TalkTalk消息或拨打客服电话与我们沟通。</strong>",
    "collectionDescription": "从简约白色到鲜明配色，<br>寻找契合你品味的组合。",
    "galleryLabel": "十一款定制订单示例鞋款",
    "specialContact": "客服电话 010-3481-5598 ↗"
  },
  "es": {
    "faqIndex": "04 / Antes de pedir",
    "faqTitle": "Preguntas<br><em>y respuestas.</em>",
    "faqIntro": "Del pedido al cuidado de tu par.",
    "navFaq": "Preguntas",
    "identityCaption": "JIDOKAAN se fabrica<br><strong>en Corea del Sur.</strong>",
    "emblemAlt": "Logotipo JIDOKAAN — Made in Korea",
    "process2": "Guarda tu diseño y pide",
    "process2Description": "Guarda una captura de tu combinación. Para pedidos dentro de Corea del Sur, compra a través de Naver Smart Store.",
    "process3": "Revisa Naver TalkTalk",
    "process3Description": "Después del pedido, revisa el mensaje de Naver TalkTalk enviado por nuestro equipo.",
    "orderIndex": "05 / Crea tus botas de boxeo",
    "faqQ1": "¿Cómo hago un pedido?",
    "faqA1": "<ol><li>Crea tu combinación de colores en el simulador de este sitio.</li><li>Haz una captura del diseño terminado y guárdala.</li><li>Para pedidos dentro de Corea del Sur, compra en nuestra tienda Naver Smart Store.</li><li>Tras el pedido, <strong>revisa el mensaje de Naver TalkTalk que te enviará nuestro equipo.</strong></li></ol>",
    "faqQ2": "¿Cuánto tarda la fabricación?",
    "faqA2": "<p>Calcula aproximadamente <strong>30 días laborables</strong>. El despacho suele realizarse, de media, en 2–3 semanas, aunque puede variar según el volumen de pedidos y la disponibilidad de materiales.</p><p>El transporte después del despacho requiere tiempo adicional.</p>",
    "faqQ3": "¿Cómo elijo la talla?",
    "faqA3": "<p>Muchos clientes con pies anchos que suelen usar la misma talla en distintos zapatos nos han indicado que esa misma talla les queda bien en JIDOKAAN.</p><p>Para un pie de forma estándar, solemos recomendar <strong>una talla menos</strong> que en las zapatillas Nike o Adidas habituales. El ajuste varía según la marca, el modelo y el pie. Si tienes dudas, indícanos el modelo y la talla que usas antes de pedir.</p>",
    "faqQ4": "¿Puedo cambiar o devolver el producto?",
    "faqA4": "<p>Cada par se fabrica según tus indicaciones y resulta difícil revenderlo. Los cambios y devoluciones por cambio de opinión se restringen <strong>cuando se cumplen los requisitos legales, incluidos el aviso previo individual y el consentimiento escrito o electrónico.</strong></p><p>Si se confirma un defecto de fabricación o una diferencia respecto al pedido, te informaremos sobre la reparación gratuita o la nueva fabricación en las mismas condiciones. Evaluamos el pedido, el estado del producto y los criterios de fabricación. Se mantienen los derechos de cambio o reembolso reconocidos por la ley.</p>",
    "faqQ5": "¿Cuánto pesan las botas?",
    "faqA5": "<p>Alrededor de <strong>280 g para la talla 260</strong>. El peso puede variar ligeramente según los materiales y la configuración elegidos.</p>",
    "faqQ6": "¿Se puede reparar o cambiar la suela?",
    "faqA6": "<p>Ofrecemos reparación si la suela se despega con el uso o necesita un reemplazo.</p><ul><li><strong>Refuerzo sencillo: gratuito durante seis meses</strong></li><li><strong>Cambio de suela: 60.000 wones coreanos</strong></li></ul><p>Antes de enviar el producto, contacta con nosotros y adjunta fotos de su estado.</p>",
    "faqQ7": "¿Se pueden lavar?",
    "faqA7": "<p>Las zonas de tejido sucias se pueden limpiar suavemente con una pequeña cantidad de detergente suave. Al ser la piel vacuna el material principal, <strong>no recomendamos la lavadora, el remojo ni el lavado completo con agua.</strong></p>",
    "faqQ8": "¿Puedo pedir una talla distinta para cada pie?",
    "faqA8": "<p><strong>Sí.</strong> Lo recomendamos si ya has usado JIDOKAAN y conoces la talla adecuada para cada pie.</p><p>No recomendamos pedir tallas distintas sin conocer primero cómo te queda nuestro calzado.</p>",
    "faqQ9": "¿Qué se incluye en el precio?",
    "faqA9": "<p>JIDOKAAN fabrica <strong>cada par a mano en Corea del Sur</strong>, con la combinación elegida por el cliente. Un par requiere más de diez horas de trabajo, sin contar el secado del adhesivo.</p><p>El precio refleja el tiempo y la mano de obra de artesanos cualificados, además del coste de los materiales.</p>",
    "faqQ10": "¿Qué acabado debo esperar de un producto artesanal?",
    "faqA10": "<p>La fabricación artesanal es un <strong>método de producción</strong> que permite atender las preferencias de una persona. No significa que todas las partes estén completamente libres de pequeñas variaciones.</p><p>El trabajo manual puede producir pequeñas diferencias en el espaciado de las puntadas o los acabados. Distinguimos estas características de los defectos de fabricación que afectan a la funcionalidad o la durabilidad.</p>",
    "mobileFaq": "Preguntas <span>04</span>",
    "look0": "Blanco · Oro",
    "look1": "Azul marino · Blanco",
    "look2": "Rojo · Negro",
    "look3": "Verde · Rojo",
    "look4": "Plata · Oro",
    "look5": "Blanco · Rojo",
    "look6": "Rosa · Negro",
    "look7": "Amarillo · Negro",
    "look8": "Negro · Oro",
    "look9": "Blanco total",
    "look10": "Blanco · Negro",
    "specialDescription": "Los pedidos especiales permiten utilizar cueros distintos de nuestra selección habitual, además de materiales con estampados o texturas especiales.<br><br>El simulador de pedidos especiales está en preparación. Puedes ver diversos ejemplos en las páginas de detalle de los productos del sitio.<br><br><strong>Antes de realizar un pedido especial, consúltanos por mensaje de Naver TalkTalk o llamando a nuestro número de atención al cliente.</strong>",
    "collectionDescription": "Del blanco discreto a combinaciones de colores intensos.<br>Descubre la combinación que va contigo.",
    "galleryLabel": "Once ejemplos de pedidos personalizados",
    "specialContact": "Atención al cliente: 010-3481-5598 ↗"
  }
};
