export default  {
  "ko": {
    "specialGalleryIndex": "02 / 스페셜오더 컬렉션",
    "specialGalleryTitle": "색상을 넘어,<br><em>소재까지.</em>",
    "specialGalleryLabel": "스페셜오더 예시 제품",
    "specialGalleryDescription": "다른 가죽과 특수 패턴·무늬 소재를 활용한 제작 예시입니다. 원하시는 소재와 제작 가능 여부는 주문 전 상담해 주세요.",
    "specialGalleryInfo": "스페셜오더 제작 안내 ↗",
    "specialSwipe": "좌우로 넘겨 예시를 살펴보세요",
    "specialViewExamples": "스페셜오더 예시 보기 ↓",
    "specialDialogIndex": "지도칸 스페셜오더 컬렉션",
    "specialExampleProduct": "스페셜오더 예시 제품입니다. 소재와 제작 가능 여부는 주문 전 네이버 톡톡 메시지 또는 고객센터 전화로 문의해 주세요.",
    "specialLook0": "블랙 패턴 · 블루",
    "specialLook1": "올리브 패턴 · 화이트",
    "specialLook2": "카무플라주 · 그레이",
    "specialLook3": "데님 패턴 · 네이비",
    "specialLook4": "체크 패턴 · 블랙"
  },
  "en": {
    "specialGalleryIndex": "02 / Special-order collection",
    "specialGalleryTitle": "Beyond colour.<br><em>Into materials.</em>",
    "specialGalleryLabel": "Special-order example",
    "specialGalleryDescription": "Examples made with alternative leathers and materials featuring special patterns or textures. Please discuss your preferred material and production options with us before ordering.",
    "specialGalleryInfo": "About special orders ↗",
    "specialSwipe": "Swipe to explore the examples",
    "specialViewExamples": "View special-order examples ↓",
    "specialDialogIndex": "JIDOKAAN special-order collection",
    "specialExampleProduct": "A special-order example. Before ordering, ask about materials and production options via Naver TalkTalk message or our customer service phone number.",
    "specialLook0": "Black pattern · Blue",
    "specialLook1": "Olive pattern · White",
    "specialLook2": "Camouflage · Grey",
    "specialLook3": "Denim pattern · Navy",
    "specialLook4": "Check pattern · Black"
  },
  "ja": {
    "specialGalleryIndex": "02 / スペシャルオーダーコレクション",
    "specialGalleryTitle": "カラーの先に、<br><em>素材の選択を。</em>",
    "specialGalleryLabel": "スペシャルオーダー製作例",
    "specialGalleryDescription": "通常とは異なるレザーや、特殊な柄・模様の素材を使用した製作例です。ご希望の素材や製作の可否については、ご注文前にご相談ください。",
    "specialGalleryInfo": "スペシャルオーダーのご案内 ↗",
    "specialSwipe": "左右にスワイプして製作例を見る",
    "specialViewExamples": "スペシャルオーダー製作例を見る ↓",
    "specialDialogIndex": "JIDOKAAN スペシャルオーダーコレクション",
    "specialExampleProduct": "スペシャルオーダーの製作例です。素材や製作の可否は、ご注文前にNaver TalkTalkのメッセージ、またはカスタマーセンターへのお電話でお問い合わせください。",
    "specialLook0": "ブラック柄 · ブルー",
    "specialLook1": "オリーブ柄 · ホワイト",
    "specialLook2": "カモフラージュ · グレー",
    "specialLook3": "デニム柄 · ネイビー",
    "specialLook4": "チェック柄 · ブラック"
  },
  "zh": {
    "specialGalleryIndex": "02 / 特别定制系列",
    "specialGalleryTitle": "不止于色彩，<br><em>更在于材质。</em>",
    "specialGalleryLabel": "特别定制示例鞋款",
    "specialGalleryDescription": "采用其他皮革及特殊图案、纹理材质的制作示例。请在下单前咨询您希望使用的材质及制作可行性。",
    "specialGalleryInfo": "特别定制说明 ↗",
    "specialSwipe": "左右滑动查看示例",
    "specialViewExamples": "查看特别定制示例 ↓",
    "specialDialogIndex": "JIDOKAAN 特别定制系列",
    "specialExampleProduct": "此鞋款为特别定制示例。请在下单前通过Naver TalkTalk消息或客服电话咨询材质及制作可行性。",
    "specialLook0": "黑色纹理 · 蓝色",
    "specialLook1": "橄榄绿纹理 · 白色",
    "specialLook2": "迷彩 · 灰色",
    "specialLook3": "牛仔纹理 · 海军蓝",
    "specialLook4": "格纹 · 黑色"
  },
  "es": {
    "specialGalleryIndex": "02 / Colección de pedidos especiales",
    "specialGalleryTitle": "Más allá del color.<br><em>Elige el material.</em>",
    "specialGalleryLabel": "Ejemplo de pedido especial",
    "specialGalleryDescription": "Ejemplos realizados con otros cueros y materiales con estampados o texturas especiales. Antes de pedir, consúltanos sobre el material que buscas y las posibilidades de fabricación.",
    "specialGalleryInfo": "Información de pedidos especiales ↗",
    "specialSwipe": "Desliza para explorar los ejemplos",
    "specialViewExamples": "Ver ejemplos de pedidos especiales ↓",
    "specialDialogIndex": "Colección de pedidos especiales JIDOKAAN",
    "specialExampleProduct": "Ejemplo de pedido especial. Antes de pedir, consulta los materiales y las posibilidades de fabricación por mensaje de Naver TalkTalk o por teléfono de atención al cliente.",
    "specialLook0": "Textura negra · Azul",
    "specialLook1": "Textura oliva · Blanco",
    "specialLook2": "Camuflaje · Gris",
    "specialLook3": "Textura denim · Azul marino",
    "specialLook4": "Cuadros · Negro"
  }
};
