/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomizeRouteImport } from './routes/customize'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as ApiCatalogRouteImport } from './routes/api/catalog'
import { Route as ApiInboxRouteImport } from './routes/api/inbox'
import { Route as ApiLoginProvidersRouteImport } from './routes/api/login-providers'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiReviewsRouteImport } from './routes/api/reviews'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProductsUploadSplatRouteImport } from './routes/products/upload/$'
import { Route as ProductsVideoSplatRouteImport } from './routes/products/video/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeRoute = CustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboxRoute = ApiInboxRouteImport.update({
  id: '/api/inbox',
  path: '/api/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginProvidersRoute = ApiLoginProvidersRouteImport.update({
  id: '/api/login-providers',
  path: '/api/login-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsRoute = ApiReviewsRouteImport.update({
  id: '/api/reviews',
  path: '/api/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsUploadSplatRoute = ProductsUploadSplatRouteImport.update({
  id: '/products/upload/$',
  path: '/products/upload/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsVideoSplatRoute = ProductsVideoSplatRouteImport.update({
  id: '/products/video/$',
  path: '/products/video/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/customize': typeof CustomizeRoute
  '/faq': typeof FaqRoute
  '/handoff': typeof HandoffRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/login-providers': typeof ApiLoginProvidersRoute
  '/api/media': typeof ApiMediaRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/products/upload/$': typeof ProductsUploadSplatRoute
  '/products/video/$': typeof ProductsVideoSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/customize': typeof CustomizeRoute
  '/faq': typeof FaqRoute
  '/handoff': typeof HandoffRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/login-providers': typeof ApiLoginProvidersRoute
  '/api/media': typeof ApiMediaRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/products/upload/$': typeof ProductsUploadSplatRoute
  '/products/video/$': typeof ProductsVideoSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/customize': typeof CustomizeRoute
  '/faq': typeof FaqRoute
  '/handoff': typeof HandoffRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/login-providers': typeof ApiLoginProvidersRoute
  '/api/media': typeof ApiMediaRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/reviews': typeof ApiReviewsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/products/upload/$': typeof ProductsUploadSplatRoute
  '/products/video/$': typeof ProductsVideoSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/checkout'
    | '/contact'
    | '/customize'
    | '/faq'
    | '/handoff'
    | '/login'
    | '/order-success'
    | '/orders'
    | '/shipping'
    | '/shop'
    | '/api/analytics'
    | '/api/catalog'
    | '/api/inbox'
    | '/api/login-providers'
    | '/api/media'
    | '/api/orders'
    | '/api/reviews'
    | '/products/$productId'
    | '/api/auth/$'
    | '/products/upload/$'
    | '/products/video/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/checkout'
    | '/contact'
    | '/customize'
    | '/faq'
    | '/handoff'
    | '/login'
    | '/order-success'
    | '/orders'
    | '/shipping'
    | '/shop'
    | '/api/analytics'
    | '/api/catalog'
    | '/api/inbox'
    | '/api/login-providers'
    | '/api/media'
    | '/api/orders'
    | '/api/reviews'
    | '/products/$productId'
    | '/api/auth/$'
    | '/products/upload/$'
    | '/products/video/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/checkout'
    | '/contact'
    | '/customize'
    | '/faq'
    | '/handoff'
    | '/login'
    | '/order-success'
    | '/orders'
    | '/shipping'
    | '/shop'
    | '/api/analytics'
    | '/api/catalog'
    | '/api/inbox'
    | '/api/login-providers'
    | '/api/media'
    | '/api/orders'
    | '/api/reviews'
    | '/products/$productId'
    | '/api/auth/$'
    | '/products/upload/$'
    | '/products/video/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CustomizeRoute: typeof CustomizeRoute
  FaqRoute: typeof FaqRoute
  HandoffRoute: typeof HandoffRoute
  LoginRoute: typeof LoginRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  OrdersRoute: typeof OrdersRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiInboxRoute: typeof ApiInboxRoute
  ApiLoginProvidersRoute: typeof ApiLoginProvidersRoute
  ApiMediaRoute: typeof ApiMediaRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiReviewsRoute: typeof ApiReviewsRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ProductsUploadSplatRoute: typeof ProductsUploadSplatRoute
  ProductsVideoSplatRoute: typeof ProductsVideoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize': {
      id: '/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof CustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox': {
      id: '/api/inbox'
      path: '/api/inbox'
      fullPath: '/api/inbox'
      preLoaderRoute: typeof ApiInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login-providers': {
      id: '/api/login-providers'
      path: '/api/login-providers'
      fullPath: '/api/login-providers'
      preLoaderRoute: typeof ApiLoginProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews': {
      id: '/api/reviews'
      path: '/api/reviews'
      fullPath: '/api/reviews'
      preLoaderRoute: typeof ApiReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/upload/$': {
      id: '/products/upload/$'
      path: '/products/upload/$'
      fullPath: '/products/upload/$'
      preLoaderRoute: typeof ProductsUploadSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/video/$': {
      id: '/products/video/$'
      path: '/products/video/$'
      fullPath: '/products/video/$'
      preLoaderRoute: typeof ProductsVideoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CustomizeRoute: CustomizeRoute,
  FaqRoute: FaqRoute,
  HandoffRoute: HandoffRoute,
  LoginRoute: LoginRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  OrdersRoute: OrdersRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  ApiInboxRoute: ApiInboxRoute,
  ApiLoginProvidersRoute: ApiLoginProvidersRoute,
  ApiMediaRoute: ApiMediaRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiReviewsRoute: ApiReviewsRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ProductsUploadSplatRoute: ProductsUploadSplatRoute,
  ProductsVideoSplatRoute: ProductsVideoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
